apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fireisp.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fireisp.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
