-- =============================================================================
-- Migration 274: CPE device registry — cpe_devices, cpe_parameters, cpe_tasks (§8.1)
-- =============================================================================

CREATE TABLE IF NOT EXISTS cpe_devices (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id     BIGINT UNSIGNED NULL,
    serial_number       VARCHAR(64)     NOT NULL,
    oui                 VARCHAR(6)      NOT NULL COMMENT 'OUI from CWMP DeviceId.OUI (6 hex chars)',
    product_class       VARCHAR(64)     NULL,
    hardware_version    VARCHAR(64)     NULL,
    software_version    VARCHAR(64)     NULL,
    firmware_version    VARCHAR(64)     NULL,
    manufacturer        VARCHAR(100)    NULL,
    model_name          VARCHAR(100)    NULL,
    acs_username        VARCHAR(100)    NULL,
    acs_password_hash   VARCHAR(255)    NULL,
    device_id           BIGINT UNSIGNED NULL COMMENT 'FK to devices table (indoor_cpe/outdoor_cpe types)',
    contract_id         BIGINT UNSIGNED NULL,
    cpe_profile_id      BIGINT UNSIGNED NULL COMMENT 'FK to cpe_profiles, added in migration 276',
    status              ENUM('new','provisioning','active','error','offline') NOT NULL DEFAULT 'new',
    last_inform_at      DATETIME        NULL,
    last_inform_ip      VARCHAR(45)     NULL,
    wan_ip              VARCHAR(45)     NULL,
    lan_subnet          VARCHAR(18)     NULL,
    wifi_ssid           VARCHAR(64)     NULL,
    notes               TEXT            NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at          DATETIME        NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cpe_devices_serial_oui (serial_number, oui),
    KEY idx_cpe_devices_organization_id (organization_id),
    KEY idx_cpe_devices_status (status),
    KEY idx_cpe_devices_device_id (device_id),
    KEY idx_cpe_devices_contract_id (contract_id),
    KEY idx_cpe_devices_cpe_profile_id (cpe_profile_id),
    KEY idx_cpe_devices_deleted_at (deleted_at),
    CONSTRAINT fk_cpe_devices_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_devices_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_devices_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='TR-069/CWMP CPE device registry (§8.1)';

CREATE TABLE IF NOT EXISTS cpe_parameters (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cpe_device_id       BIGINT UNSIGNED NOT NULL,
    organization_id     BIGINT UNSIGNED NULL,
    parameter_path      VARCHAR(512)    NOT NULL COMMENT 'TR-069 parameter path e.g. Device.WiFi.SSID.1.SSID',
    parameter_value     TEXT            NULL,
    is_writable         TINYINT(1)      NOT NULL DEFAULT 0,
    last_fetched_at     DATETIME        NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cpe_param (cpe_device_id, parameter_path(255)),
    KEY idx_cpe_parameters_org (organization_id),
    KEY idx_cpe_parameters_cpe (cpe_device_id),
    CONSTRAINT fk_cpe_parameters_device FOREIGN KEY (cpe_device_id) REFERENCES cpe_devices(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_parameters_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='TR-069 parameter tree per CPE (§8.1)';

CREATE TABLE IF NOT EXISTS cpe_tasks (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id     BIGINT UNSIGNED NULL,
    cpe_device_id       BIGINT UNSIGNED NOT NULL,
    task_type           ENUM('get_parameter_values','set_parameter_values','get_parameter_names','download','reboot','factory_reset','add_object','delete_object') NOT NULL,
    parameters          JSON            NULL COMMENT 'For set: [{path, value}], for get: [path,...], for download: {url, fileType, fileSize}',
    status              ENUM('queued','in_progress','done','failed') NOT NULL DEFAULT 'queued',
    priority            TINYINT UNSIGNED NOT NULL DEFAULT 5 COMMENT '1=highest 10=lowest',
    result              JSON            NULL,
    error_message       TEXT            NULL,
    created_by          BIGINT UNSIGNED NULL,
    queued_at           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          DATETIME        NULL,
    completed_at        DATETIME        NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_cpe_tasks_org (organization_id),
    KEY idx_cpe_tasks_device_status (cpe_device_id, status),
    KEY idx_cpe_tasks_status (status),
    CONSTRAINT fk_cpe_tasks_device FOREIGN KEY (cpe_device_id) REFERENCES cpe_devices(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_tasks_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_tasks_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Queued CWMP tasks per CPE device (§8.1)';
