-- =============================================================================
-- Migration 275: CPE profiles, parameter mappings, firmware tables (§8.1/§8.2)
-- =============================================================================

CREATE TABLE IF NOT EXISTS cpe_profiles (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id         BIGINT UNSIGNED NULL,
    name                    VARCHAR(100)    NOT NULL,
    description             TEXT            NULL,
    parent_profile_id       BIGINT UNSIGNED NULL COMMENT 'NULL = base profile; non-null = child that inherits+overrides',
    plan_id                 BIGINT UNSIGNED NULL COMMENT 'FK to plans — auto-apply this profile for CPEs on this plan',
    manufacturer            VARCHAR(100)    NULL COMMENT 'NULL = any manufacturer',
    model_name              VARCHAR(100)    NULL COMMENT 'NULL = any model',
    wifi_ssid_template      VARCHAR(64)     NULL COMMENT 'Template string, {{serial}} substituted at provision time',
    wifi_security           VARCHAR(20)     NULL DEFAULT 'WPA2-PSK',
    wifi_channel            TINYINT UNSIGNED NULL,
    wifi_band               ENUM('2.4GHz','5GHz','dual') NULL DEFAULT 'dual',
    wan_mode                ENUM('dhcp','pppoe','static') NULL DEFAULT 'dhcp',
    wan_vlan_id             SMALLINT UNSIGNED NULL,
    parameters              JSON            NULL COMMENT 'Static parameter key/value map to push on provision',
    status                  ENUM('active','inactive','draft') NOT NULL DEFAULT 'active',
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at              DATETIME        NULL,
    PRIMARY KEY (id),
    KEY idx_cpe_profiles_org (organization_id),
    KEY idx_cpe_profiles_plan (plan_id),
    KEY idx_cpe_profiles_parent (parent_profile_id),
    KEY idx_cpe_profiles_deleted_at (deleted_at),
    CONSTRAINT fk_cpe_profiles_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_profiles_plan FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_profiles_parent FOREIGN KEY (parent_profile_id) REFERENCES cpe_profiles(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CPE provisioning profiles per service plan (§8.2)';

CREATE TABLE IF NOT EXISTS cpe_parameter_mappings (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id     BIGINT UNSIGNED NULL,
    cpe_profile_id      BIGINT UNSIGNED NOT NULL,
    parameter_path      VARCHAR(512)    NOT NULL COMMENT 'TR-069 parameter path',
    source_type         ENUM('static','contract_field','plan_field','device_field') NOT NULL DEFAULT 'static',
    source_field        VARCHAR(100)    NULL COMMENT 'Field name on contract/plan/device when source_type != static',
    static_value        TEXT            NULL COMMENT 'Value when source_type=static',
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_cpe_param_mappings_org (organization_id),
    KEY idx_cpe_param_mappings_profile (cpe_profile_id),
    CONSTRAINT fk_cpe_param_mappings_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_param_mappings_profile FOREIGN KEY (cpe_profile_id) REFERENCES cpe_profiles(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Automatic parameter mapping rules for CPE profiles (§8.2)';

CREATE TABLE IF NOT EXISTS cpe_firmware_versions (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id     BIGINT UNSIGNED NULL,
    manufacturer        VARCHAR(100)    NOT NULL,
    model_name          VARCHAR(100)    NOT NULL,
    version             VARCHAR(64)     NOT NULL,
    firmware_url        VARCHAR(512)    NOT NULL,
    file_size_bytes     BIGINT UNSIGNED NULL,
    checksum            VARCHAR(128)    NULL,
    checksum_type       ENUM('md5','sha1','sha256') NULL DEFAULT 'md5',
    is_stable           TINYINT(1)      NOT NULL DEFAULT 1,
    release_notes       TEXT            NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at          DATETIME        NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cpe_fw_ver (manufacturer, model_name, version),
    KEY idx_cpe_fw_org (organization_id),
    KEY idx_cpe_fw_deleted_at (deleted_at),
    CONSTRAINT fk_cpe_fw_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Firmware version inventory per CPE model (§8.1)';

CREATE TABLE IF NOT EXISTS cpe_firmware_campaigns (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id         BIGINT UNSIGNED NULL,
    name                    VARCHAR(100)    NOT NULL,
    firmware_version_id     BIGINT UNSIGNED NOT NULL,
    target_manufacturer     VARCHAR(100)    NULL,
    target_model            VARCHAR(100)    NULL,
    target_profile_id       BIGINT UNSIGNED NULL,
    target_device_ids       JSON            NULL COMMENT 'Array of cpe_device IDs for ad-hoc targeting',
    status                  ENUM('scheduled','running','done','failed','cancelled') NOT NULL DEFAULT 'scheduled',
    scheduled_at            DATETIME        NULL,
    started_at              DATETIME        NULL,
    completed_at            DATETIME        NULL,
    total_devices           INT UNSIGNED    NOT NULL DEFAULT 0,
    completed_devices       INT UNSIGNED    NOT NULL DEFAULT 0,
    failed_devices          INT UNSIGNED    NOT NULL DEFAULT 0,
    result_summary          JSON            NULL,
    created_by              BIGINT UNSIGNED NULL,
    notes                   TEXT            NULL,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at              DATETIME        NULL,
    PRIMARY KEY (id),
    KEY idx_cpe_fw_camp_org (organization_id),
    KEY idx_cpe_fw_camp_status (status),
    KEY idx_cpe_fw_camp_scheduled_at (scheduled_at),
    KEY idx_cpe_fw_camp_deleted_at (deleted_at),
    CONSTRAINT fk_cpe_fw_camp_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_fw_camp_fw FOREIGN KEY (firmware_version_id) REFERENCES cpe_firmware_versions(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_fw_camp_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_cpe_fw_camp_profile FOREIGN KEY (target_profile_id) REFERENCES cpe_profiles(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Batch firmware upgrade campaigns (§8.1)';
