-- Rollback 200: Remove plan billing feature columns and plan_throttle_logs table

DROP TABLE IF EXISTS plan_throttle_logs;

DROP PROCEDURE IF EXISTS rollback_200_plan_billing_features;
DELIMITER //
CREATE PROCEDURE rollback_200_plan_billing_features()
BEGIN
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'trial_price') THEN
    ALTER TABLE plans DROP COLUMN trial_price;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'trial_days') THEN
    ALTER TABLE plans DROP COLUMN trial_days;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'overage_price_per_gb') THEN
    ALTER TABLE plans DROP COLUMN overage_price_per_gb;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'overage_mode') THEN
    ALTER TABLE plans DROP COLUMN overage_mode;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'fup_upload_speed_mbps') THEN
    ALTER TABLE plans DROP COLUMN fup_upload_speed_mbps;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'fup_download_speed_mbps') THEN
    ALTER TABLE plans DROP COLUMN fup_download_speed_mbps;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'fup_threshold_percent') THEN
    ALTER TABLE plans DROP COLUMN fup_threshold_percent;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'fup_threshold_gb') THEN
    ALTER TABLE plans DROP COLUMN fup_threshold_gb;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'radius_rate_limit_template') THEN
    ALTER TABLE plans DROP COLUMN radius_rate_limit_template;
  END IF;
  IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'plans' AND COLUMN_NAME = 'radius_vendor') THEN
    ALTER TABLE plans DROP COLUMN radius_vendor;
  END IF;
END //
DELIMITER ;
CALL rollback_200_plan_billing_features();
DROP PROCEDURE IF EXISTS rollback_200_plan_billing_features;
