-- Rollback 377: Seed missing route permissions (Pattern G backfill)
-- role_permissions rows cascade via fk_role_permissions_permission ON DELETE CASCADE
DELETE FROM permissions WHERE name IN (
  'api_tokens.create', 'api_tokens.delete', 'api_tokens.update',
  'api_tokens.view', 'cfdi_documents.create', 'cfdi_documents.update',
  'cfdi_documents.view', 'clients.export', 'connection_logs.view',
  'contracts.export', 'coverage_zones.create', 'coverage_zones.delete',
  'coverage_zones.update', 'coverage_zones.view', 'credit_notes.create',
  'credit_notes.delete', 'credit_notes.update', 'credit_notes.view',
  'csd_certificates.create', 'csd_certificates.delete', 'csd_certificates.update',
  'csd_certificates.view', 'device_config_backups.create', 'device_config_backups.delete',
  'device_config_backups.update', 'device_config_backups.view', 'expenses.delete',
  'facturas_publicas.create', 'facturas_publicas.update', 'facturas_publicas.view',
  'files.create', 'files.delete', 'files.update',
  'files.view', 'inventory.delete', 'invoices.export',
  'ip_assignments.create', 'ip_assignments.delete', 'ip_assignments.update',
  'ip_assignments.view', 'ip_pools.create', 'ip_pools.delete',
  'ip_pools.update', 'ip_pools.view', 'network_health.view',
  'network_links.create', 'network_links.delete', 'network_links.update',
  'network_links.view', 'organizations.create', 'organizations.delete',
  'outages.create', 'outages.delete', 'outages.update',
  'outages.view', 'pac_providers.create', 'pac_providers.delete',
  'pac_providers.update', 'pac_providers.view', 'payment_gateways.create',
  'payment_gateways.delete', 'payment_gateways.update', 'payment_gateways.view',
  'payment_transactions.view', 'payments.export', 'promotions.create',
  'promotions.delete', 'promotions.update', 'promotions.view',
  'quotes.create', 'quotes.delete', 'quotes.update',
  'quotes.view', 'recurring_payment_profiles.create', 'recurring_payment_profiles.delete',
  'recurring_payment_profiles.update', 'recurring_payment_profiles.view', 'revenue_summary.view',
  'roles.manage', 'roles.view', 'scheduled_tasks.create',
  'scheduled_tasks.delete', 'scheduled_tasks.update', 'scheduled_tasks.view',
  'service_areas.create', 'service_areas.delete', 'service_areas.update',
  'service_areas.view', 'sites.create', 'sites.delete',
  'sites.update', 'sites.view', 'sla_definitions.create',
  'sla_definitions.delete', 'sla_definitions.update', 'sla_definitions.view',
  'sms.send', 'sms.view', 'snmp_profiles.create',
  'snmp_profiles.delete', 'snmp_profiles.update', 'snmp_profiles.view',
  'speed_tests.create', 'speed_tests.delete', 'speed_tests.update',
  'speed_tests.view', 'suspension_rules.create', 'suspension_rules.delete',
  'suspension_rules.update', 'suspension_rules.view', 'tax_rates.create',
  'tax_rates.delete', 'tax_rates.update', 'tax_rates.view',
  'tax_rules.create', 'tax_rules.delete', 'tax_rules.update',
  'tax_rules.view', 'vlans.create', 'vlans.delete',
  'vlans.update', 'vlans.view', 'webhooks.create',
  'webhooks.delete', 'webhooks.update', 'webhooks.view'
);
